### ISSUE TITLE
Translate DEFAULT-keyword to nothing in nested object notation

### ISSUE THREAD

**Issue by tvartom** [mertasan/tailwindcss-variables#9]
When using nestet object notation, DEFAULT doesn't seems to be acknowledged the same way as with Tailwind.

Tailwind generate the colors in this example as: `testblue-light`, `testblue` and `testblue-darker`.
It would be nice if this plugin did the same.

```
// tailwind.config.js
const colors = {
	testblue: {
		lighter: '#5883BB',
		DEFAULT: '#265796',
		darker: '#184176',
	},
};

module.exports = {
  theme: {
    colors,
    variables: {
      DEFAULT: {
        colors,
      },
    },
  },
  plugins: [
    require('@mertasan/tailwindcss-variables'),
  ],
};
```

Current output:
```
:root {
    --colors-testblue-lighter:#5883bb;
    --colors-testblue--d-e-f-a-u-l-t:#265796;
    --colors-testblue-darker:#184176;
}
```

Desired output:
```
:root {
    --colors-testblue-lighter:#5883bb;
    --colors-testblue:#265796;
    --colors-testblue-darker:#184176;
}
```

I use this setup because my primary development is using TailwindCSS as is, with Vue. I want the colors to be declared so `Tailwind CSS IntelliSense` works with showing colors in VS-Code. (Which mean I can't use variables as Tailwind-colors)
The exported variables are for some external components where I want to use the same colors. (Using PrimeVue).
This is working, so this feature is really just to make the variable-name prettier.

(And thank you very much for this nice plugin!)

**Comment by mertasan** [comment]
It seems that the problem is not with the this plugin. tailwindlabs/tailwindcss#1694 postcss/postcss-js#46

I tried it this way and realized it was not related to plugin.

https://github.com/tailwindlabs/tailwindcss/blob/6d51f9a08a20b81625cb89259f9e971280206155/src/plugins/backgroundColor.js#L18

<img width="673" alt="screenshot 181" src="https://user-images.githubusercontent.com/13007665/117885834-00f8d980-b2b7-11eb-8c54-d6cfb700b9d2.png">

<img width="657" alt="screenshot 180" src="https://user-images.githubusercontent.com/13007665/117885843-0524f700-b2b7-11eb-8eb0-eb7a36aac988.png">

**But I have good news.** 

I've provided an exception for the DEFAULT. In this way, it became more useful.

please upgrade the plugin to v1.1.4 👍

https://github.com/mertasan/tailwindcss-variables/blob/dcf9bef334d644f1d9783abd7908b0985bf2de6e/__tests__/nested-variables.test.js#L9-L52

https://github.com/mertasan/tailwindcss-variables/blob/dcf9bef334d644f1d9783abd7908b0985bf2de6e/__tests__/nested-variables.test.js#L59-L90

**Comment by tvartom** [comment]
Great work and again really quick!
Now it works with DEFAULT as expected!
Thank you!

A quess the built in feature is made for camelCase, which doen't look to good on UPPERCASE.
